# Generated by Django 5.2 on 2025-04-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Permission Name')),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='Permission Codename')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'authentication_permission',
                'ordering': ['name'],
            },
        ),
    ]
