# Generated by Django 5.2 on 2025-04-25 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_code', to='master.accountgroup')),
            ],
            options={
                'verbose_name': 'Account Types',
                'verbose_name_plural': 'Account Types',
                'db_table': 'account_types',
            },
        ),
    ]
