# Generated by Django 5.2 on 2025-04-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_accounttypes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounttypes',
            name='account_code',
        ),
        migrations.AddField(
            model_name='accounttypes',
            name='code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
